application: todlo
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /dashboard/settings.*
  script: settings.py
  login: required

- url: /dashboard.*
  script: dashboard.py
  login: required

- url: /textmarks.*
  script: textmarks.py

- url: .*
  script: main.py
